export type ViewKey = 'overview' | 'prediction' | 'what-if' | 'intelligence' | 'validation' | 'features' | 'operations' | 'reports' | 'architecture'

export type EngineeringInputs = { outerDiameter:number; sectionWidth:number; nsd:number; shoulderDiameter:number; rimWidth:number; rimHeight:number; plyEpi:number; plies:number; breakers:number; inflationPressure:number }
export type DerivedParameters = { unloadedRadius:number; odWidthRatio:number; shoulderDrop:number }
export type ModelMetric = { name:string; mape:number; r2:number; rmse:number; status:'Champion'|'Candidate' }
export type ShapContribution = { feature:string; value:number; direction:'positive'|'negative' }
export type PredictionResponse = { predictedSlr:number; lower:number; upper:number; confidence:number; warning:string; shap:ShapContribution[]; derived:DerivedParameters }
export type DriftStatus = { label:string; value:string; status:'Healthy'|'Watch'|'Critical'; score:number }
export type ReportType = 'Validation'|'Feature'|'Prediction'

export const inputBounds: Record<keyof EngineeringInputs,{label:string; min:number; max:number; unit:string}> = {
  outerDiameter:{label:'Outer Diameter',min:400,max:2600,unit:'mm'}, sectionWidth:{label:'Section Width',min:150,max:900,unit:'mm'}, nsd:{label:'NSD',min:5,max:100,unit:'mm'}, shoulderDiameter:{label:'Shoulder Diameter',min:300,max:2500,unit:'mm'}, rimWidth:{label:'Rim Width',min:100,max:1000,unit:'mm'}, rimHeight:{label:'Rim Height',min:100,max:1000,unit:'mm'}, plyEpi:{label:'Ply EPI',min:5,max:100,unit:'EPI'}, plies:{label:'Plies',min:1,max:30,unit:'count'}, breakers:{label:'Breakers',min:0,max:12,unit:'count'}, inflationPressure:{label:'Inflation Pressure',min:10,max:150,unit:'PSI'}
}
export const defaultInputs: EngineeringInputs = { outerDiameter:1100,sectionWidth:315,nsd:22,shoulderDiameter:1040,rimWidth:250,rimHeight:480,plyEpi:24,plies:8,breakers:4,inflationPressure:100 }
export const metrics: ModelMetric[] = [{name:'Random Forest',mape:6.76,r2:.942,rmse:43.71,status:'Champion'},{name:'XGBoost',mape:7.18,r2:.935,rmse:46.28,status:'Candidate'},{name:'CatBoost',mape:7.42,r2:.928,rmse:48.06,status:'Candidate'}]
export const featureImportance = [{feature:'Shoulder Diameter',value:49.56},{feature:'Unloaded Radius',value:23.19},{feature:'Section Width',value:11.84},{feature:'Inflation Pressure',value:8.42},{feature:'Ply EPI',value:6.99}]
export const sensitivity = Array.from({length:9},(_,i)=>({od:800+i*75,slr:238+i*18.5}))
export const drift: DriftStatus[] = [{label:'Data Drift',value:'0.08 PSI',status:'Healthy',score:92},{label:'Prediction Drift',value:'0.14 mm',status:'Healthy',score:88},{label:'Performance Drift',value:'2.1% MAPE',status:'Watch',score:76}]
export function deriveInputs(i:EngineeringInputs):DerivedParameters { const radius=Math.max(i.outerDiameter-i.nsd,0)/2; return {unloadedRadius:radius,odWidthRatio:i.sectionWidth?i.outerDiameter/i.sectionWidth:0,shoulderDrop:Math.max(i.outerDiameter-i.shoulderDiameter,0)/2} }
export async function predict(inputs:EngineeringInputs):Promise<PredictionResponse>{ const d=deriveInputs(inputs); const slr=Number((150+d.unloadedRadius*.082+(inputs.inflationPressure-100)*.22+(inputs.shoulderDiameter-900)*.018).toFixed(1)); const confidence=Math.max(72,Math.min(98,94-Math.abs(inputs.outerDiameter-1100)/80-Math.abs(inputs.inflationPressure-100)/8)); return {predictedSlr:slr,lower:Number((slr-43.71).toFixed(1)),upper:Number((slr+43.71).toFixed(1)),confidence:Number(confidence.toFixed(1)),warning:inputs.inflationPressure>125?'High inflation pressure may widen the uncertainty interval.':'Within validated operating envelope.',derived:d,shap:[{feature:'Shoulder Diameter',value:(inputs.shoulderDiameter-900)*.06,direction:inputs.shoulderDiameter>=900?'positive':'negative'},{feature:'Unloaded Radius',value:(d.unloadedRadius-500)*.04,direction:d.unloadedRadius>=500?'positive':'negative'},{feature:'Inflation Pressure',value:(inputs.inflationPressure-100)*.12,direction:inputs.inflationPressure>=100?'positive':'negative'},{feature:'Section Width',value:(inputs.sectionWidth-315)*-.05,direction:inputs.sectionWidth<=315?'positive':'negative'},{feature:'Ply EPI',value:(inputs.plyEpi-24)*-.8,direction:inputs.plyEpi<=24?'positive':'negative'}]}}
export const auditLogs=['09:41:02  pipeline.validate  GroupShuffleSplit: 72 train / 19 test groups','09:41:04  data.monitor      PSI drift=0.08 threshold=0.20 status=HEALTHY','09:41:07  model.registry     random-forest-v2.4.1 promoted to champion','09:41:11  inference.service  p95 latency=182ms batch=SLR-2026-0911','09:41:15  shap.explainer     5 feature contributions emitted','09:41:18  deployment.audit   checksum verified; rollout 100% complete']
export const navItems:[ViewKey,string,string][]=[['overview','Overview','LayoutDashboard'],['prediction','SLR Prediction','Activity'],['what-if','What-If Analysis','SlidersHorizontal'],['intelligence','Model Intelligence','BrainCircuit'],['validation','Validation','BadgeCheck'],['features','Feature Intelligence','Network'],['operations','Model Operations','ServerCog'],['reports','Reports','FileText'],['architecture','System Architecture','Waypoints']]
